---
- name: Create batch Deployment
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ batch_app_id }}-deployment"
        namespace: "{{ juritcom_namespace }}"
        labels:
          app:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ batch_app_id }}"
        template:
          metadata:
            labels:
              app: "{{ batch_app_id }}"
          spec:
            nodeSelector:
              kubernetes.io/hostname: "{{ av_node_name }}"
            containers:
              - name: "{{ batch_app_id }}"
                image: "{{ juritcom_batch_image }}"
                env:
                  - name: NORMALIZATION_BATCH_SCHEDULE
                    value: "{{ normalization_batch_schedule }}"
                  - name: COMMISSIONING_DATE
                    value: "{{ commissioning_date }}"
                envFrom:
                  - configMapRef:
                      name: "api-config"
                  - secretRef:
                      name: "api-secret"
                  - configMapRef:
                      name: "s3-config"
                  - secretRef:
                      name: "s3-secret"
                volumeMounts:
                  - name: av-volume
                    mountPath: "{{ av_pdf_path }}"
            volumes:
              - name: av-volume
                hostPath:
                  path: "{{ av_host_path }}"
                  type: Directory
...
