---
- name: Creation de la ConfigMap du s3
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: s3-config
        namespace: "{{ juritcom_namespace }}"
        labels:
          app: "{{ juritcom_application }}"
      data:
        S3_URL: "{{ s3_url }}"
        S3_REGION: "{{ s3_region }}"
        S3_BUCKET_NAME_RAW: "{{ s3_bucket_name }}"
        S3_BUCKET_NAME_PDF: "{{ s3_bucket_name_pdf }}"
        S3_BUCKET_NAME_DELETION: "{{ s3_bucket_name_deletion }}"
        S3_BUCKET_NAME_NORMALIZED: "{{ s3_bucket_name_normalized }}"
        S3_ARCHIVE_SCHEDULE: "{{ s3_archive_schedule }}"
        S3_PDF_FILE_NAME_SEPARATOR: "{{ s3_pdf_file_name_separator }}"
...
