---
ansible_user: iliasaaguida
ansible_python_interpreter: "/home/{{ ansible_user }}/ansible_venv/bin/python"

api_service: "api-service"
bucket_service: "bucket-service"
juritcom_private_name: "tcm.judilibre-prive.local"

use_auth: "basic"

api_port: "3000"
doc_login: "root"
s3_region: "eu-west-paris-1"
s3_bucket_name: "juritcom-bucket"
s3_bucket_name_pdf: "juritcom-bucket-pdf"
s3_bucket_name_deletion: "juritcom-bucket-deletion"
s3_bucket_name_normalized: "juritcom-bucket-normalized"
s3_url: "http://bucket-service.juritj.svc.cluster.local:9000"
dbsder_api_url: "http://{{ api_service }}.dbsder:3000"
no_color: "true"
normalization_batch_schedule: "* * * * *"
oauth_client_id: "juritcom"
oauth_provider_url: "http://localhost:{{ api_port }}"
oauth_token_url: "{{ oauth_provider_url }}/token"
s3_archive_schedule: "0 18 * * * *"
s3_pdf_file_name_separator: "_-_-_-_"