---
ansible_user: iliasaaguida
ansible_python_interpreter: "/home/{{ ansible_user }}/ansible_venv/bin/python"

api_service: "api-service"
bucket_service: "bucket-service"
juritcom_private_name: "tcm.judilibre-prive.local"

api_port: "3000"
doc_login: "root"
s3_url: "http://{{ bucket_service }}:9000"
s3_region: "eu-west-paris-1"
s3_bucket_name: "juritcom-bucket"
s3_bucket_name_normalized: "juritcom-bucket-normalized"
dbsder_api_url: "http://{{ api_service }}.dbsder:3000"
no_color: "true"
minio_root_user: "root"
minio_browser_redirect_url: "https://{{ juritcom_private_name }}/bucket"

normalization_batch_schedule: "* * * * *"
