name: juritcom

services:
  bucket:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    command: minio server /data --console-address :9001
    volumes:
      - bucket-storage:/data
    expose: 
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root1234

  createbuckets:
    image: minio/mc
    depends_on:
      - bucket
    entrypoint: > # source: https://github.com/minio/minio/issues/4769 
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://bucket:9000 root root1234;
      /usr/bin/mc mb --ignore-existing myminio/juritcom-test-bucket &&
      /usr/bin/mc mb --ignore-existing myminio/juritcom-test-bucket-normalized &&
      /usr/bin/mc policy download myminio/juritcom-test-bucket &&
      /usr/bin/mc policy download myminio/juritcom-test-bucket-normalized &&
      /usr/bin/mc admin user svcacct add --access-key "local_access_key" --secret-key "local_secret_key" myminio root;
      exit 0;
      "

  api:
    build:
      context: ./
      target: api
    env_file:
      - docker.env
    ports:
      - 3009:3000

volumes:
  bucket-storage:
    driver: local
    name: juritcom-bucket-storage


