name: opendata

services:
  juritcom-api:
    build:
      target: api
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}

  juritcom-batch: 
    build:
      target: batch
    env_file:
      - .env
