---
- name: Creation ingress
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: ingress-route
        namespace: "{{ juritcom_namespace }}"
      spec:
        entryPoints:
          - web
        routes:
          - match: "Host(`{{ juritcom_private_name }}`) && PathPrefix(`/v1`)"
            kind: Rule
            services:
              - name: "{{ api_service }}"
                port: api
          - match: "Host(`{{ juritcom_private_name }}`) && PathPrefix(`/v1/health`)"
            kind: Rule
            services:
              - name: "{{ api_service }}"
                port: api
          - match: "Host(`{{ juritcom_private_name }}`) && PathPrefix(`/v1/decision`)" 
            kind: Rule
            services:
              - name: "{{ api_service }}"
                port: api
...
