---
- name: Creation ingress
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: ingress-route
        namespace: "{{ juritcom_namespace }}"
      spec:
        entryPoints:
          - web
        routes:
          - match: "Host(`{{ juritcom_private_name }}`) && PathPrefix(`/`)"
            kind: Rule
            services:
              - name: "{{ api_service }}"
                port: api
#            middlewares:
#              - name: "{{ api_stripprefix }}"
#          - match: "Host(`{{ juritcom_private_name }}`) && PathPrefix(`/bucket`)"
#            kind: Rule
#            services:
#              - name: "{{ bucket_service}}"
#                port: console
#            middlewares:
#              - name: "{{ bucket_stripprefix }}"

...
