---
s3_access_key: "{{ vault_s3_access_key }}"
s3_secret_key: "{{ vault_s3_secret_key }}"
doc_password: "{{ vault_doc_password }}"
jwt_client_secret: "{{ vault_jwt_client_secret}}"
jwt_secret: "{{ vault_jwt_secret }}"
jwt_issuer: "juritcom-dev"
jwt_accepted_issuers: "juritcom-dev,juritcom-preprod"

commissioning_date: "2024-12-31"
file_db_url: "{{ vault_file_db_url }}"
