---
- name: Creation secrets bucket
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: bucket-secret
        namespace: "{{ juritcom_namespace }}"
        labels:
          app: "{{ juritcom_application }}"
      type: Opaque
      data:
        MINIO_ROOT_PASSWORD: "{{ minio_root_password | b64encode }}"

...
